apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: online-store-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mariuszbrozda/production-devops-platform.git
  ref:
    branch: main
  timeout: 20s