apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: online-store
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/online-store
      sourceRef:
        kind: GitRepository
        name: online-store-repo
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: latest
  valuesFrom:
    - kind: Secret
      name: ecr-config
      valuesKey: repository
      targetPath: image.repository