apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-values
  namespace: monitoring
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        serviceMonitorSelector: {}
        ruleSelector: {}
        podMonitorSelector: {}
        probeSelector: {}
