# CD workflow to:
# Deploy AWS infrastructure (VPC, ECR, EKS etc.)
# Build and push Docker image to ECR
# Deploy app to EKS cluster (Helm Chart)
# Verify app is running in the EKS cluster and can be accessed via LoadBalancer

name: Build And Deploy

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Build and Test"]
  #   types: [completed]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Check code for syntax errors
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        # Run Tests
      - name: Test with pytest
        run: |
          pytest -q

        # Install prerequisites
      - name: Install make (make)
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Deploy infra(VPC, ECR, EKS,)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Verify Terraform
        run: terraform version

      - name: Terraform init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform validate
        run: make tf-validate

      - name: Terraform plan quietly
        working-directory: infra/terraform
        run: terraform plan -detailed-exitcode -input=false -out=tfplan -var-file=terraform.tfvars > /dev/null

      - name: Terraform apply resources
        working-directory: infra/terraform
        run: terraform apply -auto-approve

      - name: Update kubeconfig and access EKS cluster
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          kubectl get nodes

      - name: Create ECR repo secret in cluster
        run: kubectl create secret generic ecr -n default --from-literal=repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}

      # Build and push Docker image to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Tag snd Push Docker image to ECR
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}
          docker build -t online-store .
          docker tag online-store:latest ${IMAGE_URI}:latest
          docker push ${IMAGE_URI}:latest
          echo "Image uri: ${IMAGE_URI}:latest"

      # Setup and validate FluxCD
      - name: Install Flux CLI
        run: |
          curl -s https://fluxcd.io/install.sh | sudo bash

      - name: Validate Flux
        run: |
          echo "Validating Flux installation and configuration"
          flux --version
          flux check --pre

      - name: Bootstrap Flux
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          flux bootstrap github \
            --owner=${{ secrets.GIT_USER }} \
            --repository=devops-fastapi-k8-aws-helm \
            --branch=main \
            --path=deploy/clusters/flux-system \
            --personal

      - name: Flux Check
        run: flux check

      - name: Verify Helm release, deployments, and pods
        run: |
          echo "Waiting for Helm release to be deployed"
          sleep 120
          echo "Verifying helm release, deployments, and pods"
          helm list
          kubectl get deployments
          kubectl get pod

      - name: Test Application via Load Balancer
        run: |
          echo "Retrieving Load Balancer External Ip(host)"
          EXTERNAL_IP=$(kubectl get svc online-store -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "Accessing External Ip(host) by curl"
          curl $(echo "http://$EXTERNAL_IP")
          sleep 60
      - name: Clean up
        run: |
          echo "Cleaning up Helm release"
          helm uninstall online-store
          echo "Deleting ECR image"
          aws ecr batch-delete-image --repository-name ${{ secrets.ECR_REPOSITORY_NAME }} --image-ids imageTag=latest
      - name: Destroy Terraform resources
        working-directory: infra/terraform
        if: always()
        run: |
          echo "deleting Infra"
          terraform destroy -auto-approve
